template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "khan1273"
__REPO__ = "lang-kca"
__UND2C__ = "kca"
__UNDEFINED__ = "Khanty"
__UND__ = "kca"
