template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "khan1273"
__REPO__ = "lang-kca"
__UND2C__ = "kca"
__UNDEFINED__ = "Khanty"
__UND__ = "kca"
