[package]
name = "kca"
human_name = "Khanty"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.kca]
filename = "kca-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-kca"
platform = "windows"
uuid = "37A8E779-F818-4F82-A263-31FD35CC40A0"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.kca"
package = "speller-kca"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-kca-mso"
platform = "windows"
uuid = "24AE5D79-2D31-4891-9FBC-541C73119302"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-kca"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
